// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NemoFind.Infrastructure.Data;

#nullable disable

namespace NemoFind.Infrastructure.Migrations
{
    [DbContext(typeof(NemoFindDbContext))]
    partial class NemoFindDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("NemoFind.Core.Models.FileHash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("Hash");

                    b.ToTable("FileHashes");
                });

            modelBuilder.Entity("NemoFind.Core.Models.IndexedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("NemoFind.Core.Models.InvertedIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TfIdfScore")
                        .HasColumnType("REAL");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("WordId", "FileId")
                        .IsUnique();

                    b.ToTable("InvertedIndexes");
                });

            modelBuilder.Entity("NemoFind.Core.Models.SearchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SearchDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchedAt");

                    b.ToTable("SearchLogs");
                });

            modelBuilder.Entity("NemoFind.Core.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("Words");
                });

            modelBuilder.Entity("NemoFind.Core.Models.FileHash", b =>
                {
                    b.HasOne("NemoFind.Core.Models.IndexedFile", "File")
                        .WithOne("FileHash")
                        .HasForeignKey("NemoFind.Core.Models.FileHash", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("NemoFind.Core.Models.InvertedIndex", b =>
                {
                    b.HasOne("NemoFind.Core.Models.IndexedFile", "File")
                        .WithMany("InvertedIndexes")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NemoFind.Core.Models.Word", "Word")
                        .WithMany("InvertedIndexes")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("NemoFind.Core.Models.IndexedFile", b =>
                {
                    b.Navigation("FileHash");

                    b.Navigation("InvertedIndexes");
                });

            modelBuilder.Entity("NemoFind.Core.Models.Word", b =>
                {
                    b.Navigation("InvertedIndexes");
                });
#pragma warning restore 612, 618
        }
    }
}
